### ISSUE TITLE
Gráfica de "Escenario contabilizando posibles muertes" se muestra mal cuando M_o >0

### ISSUE THREAD

**Issue by pacomx** [NunezKant/COVID-19_GDL#3]
Al actualizar los parámetros para la gráfica "Escenario contabilizando posibles muertes" al corte del día 29/marzo (83 casos, 3 muertes) se muestra de forma incorrecta. Pasa cuando "M_o" (muertos) es mayor a cero.

![bug-grafica](https://user-images.githubusercontent.com/509794/77881336-006cc300-721c-11ea-9dad-07fa8a7c9c69.png)

**Comment by NunezKant** [comment]
Hola Paco, de casualidad si hiciste la proporción?

Es decir, Muertes / Población ? 

La ecuación no puede tener condiciones inciales mayores a 1.

**Comment by pacomx** [comment]
Efectivamente, me faltó eso.
Gracias.
